# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
# Mod Properties
mod_version=1.2.1
maven_group=dev.louis
archives_base_name=PromotedServer
# Dependencies
# check this on https://modmuss50.me/fabric.html
